spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpashop
    username: root
    password: 5199
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 554902514192-au1haeci8bc3hgtdf1bl6hnabuik1kug.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile


          naver:
            client-id: UpSrUewon8QXWPdDB93G
            client-secret: _EPS0YOhpJ
            redirect-uri:  "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname
              - age
            client-name: Naver

          kakao:
            client-id: 841bf57e02fe486fe15dfc6042a61b66
            client-secret: QBks46Z4YNjGIPC9C7MkbwOtyVGE8dJc
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri :  https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account



logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


